server:
  port: 8085

logging:
    level:
        org.springframework: 'DEBUG'

security:
    oauth2:
        resource:
            jwt:
                # Tells the JWT framework to fetch the public key from the authorization server during startup
                key-uri: "http://localhost:8084/oauth/token_key"
