server:
  port: 8085

config:
    oauth2:
        publicKey:
            -----BEGIN PUBLIC KEY-----
            MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNQZKqTlO/+2b4ZdhqGJzGBDlt
            b5PZmBz1ALN2YLvt341pH6i5mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE
            /myh1zM6m8cbL5cYFPyP099thbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26
            hL9dSAZuA8xExjlPmQIDAQAB
            -----END PUBLIC KEY-----

#security:
#    oauth2:
#        resource:
#            jwt:
#                # Tells the JWT framework to fetch the public key from the authorization server during startup
#                key-uri: "http://localhost:8084/oauth/token_key"