server:
    port: 8080
    contextPath: /client

security:
  basic:
    enabled: false

oauth2:
    clientId: my-trusted-client
    clientSecret: secret
    userAuthorizationUri: http://localhost:8082/oauth/authorize
    accessTokenUri: http://localhost:8082/oauth/token
    resourceUri: http://localhost:8082
